### ISSUE TITLE
[bug]webman 只能安装到1.3

### ISSUE THREAD

**Issue by 21307369** [cloudtay/ripple-driver#16]
composer require cloudtay/ripple-driver  只能安装1.3
composer require cloudtay/ripple-driver dev-main 才能装到1.5

文档里
'event_loop' => \Ripple\Drive\Workerman\Driver4::class,
实际上应该是
'event_loop' => \Ripple\Driver\Workerman\Driver4::class,

**Comment by cclilshy** [comment]
感谢支持, `tag:v1.5` 的依赖已在得到本次反馈后修正, 请清空composer缓存后重试
